tabWidth = 4
semi = false

[[overrides]]

files = "*.md"
options = { "tabWidth" = 2 }

[[overrides]]

files = "*.json"
options = { "tabWidth" = 2 }

[[overrides]]

files = "*.yml"
options = { "tabWidth" = 2 }
