site_name: Memegen.link
site_description: The free and open source API to generate memes.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/memegen
edit_uri: ""

nav:
  - Home: index.md
  - Clients: clients.md
  - Examples: examples.md

theme:
  name: mkdocs
  custom_dir: docs/theme
  nav_style: dark
  analytics:
    gtag: G-B2XT39Z5FC

plugins: []

remote_branch: site
